### ISSUE TITLE
Add configuration options

### ISSUE THREAD

**Issue by Israel-** [Israel-/fltk-dash#1]
from e-mails with @mpmc

Select the search bar position, top/bottom.
Double vs Single click.
Sizeable (not sure how it handles large app names).
Larger Icons/no icons, maybe even just icons (think the Gnome search, but a lot less heavy & flashy).
Hide/Close on app launch.

**Comment by Israel-** [comment]
This is mostly fixed in the newest AppImage version
I can't implement:
* Double vs Single click.
This is due to me not wanting to write my own event handler right now... perhaps some day.

* Larger Icons/no icons, maybe even just icons (think the Gnome search, but a lot less heavy & flashy).
'just icons' would not work for things that use default icon.  Icon size is tied to Font size, so increase the font and icon size... but FLTK will not allow them separate without some serious hacking

**Comment by mpmc** [comment]
> Double vs Single click.
This is due to me not wanting to write my own event handler right now... perhaps some day.

Either is fine :)

> Larger Icons/no icons, maybe even just icons (think the Gnome search, but a lot less heavy & flashy).
'just icons' would not work for things that use default icon. Icon size is tied to Font size, so increase the font and icon size... but FLTK will not allow them separate without some serious hacking

Icon & font size should match anyway - As long as the size increases it shouldn't be a problem!
